name: CI

# workflow triggers
on:
  # manually
  workflow_dispatch:
  # PRs on `main`
  pull_request:
    branches:
    - main

jobs:
  verify:
    name: Verify build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v6.0.2
      with:
        submodules: true

    - name: Setup Java and Maven cache
      uses: actions/setup-java@v5.2.0
      with:
        distribution: 'temurin'
        java-version: '21'
        check-latest: true
        cache: 'maven'

    - name: Prepare Vitruv-Change submodule
      run: >
        cd Vitruv-Change &&
        ./mvnw clean install
        --fail-fast
        --batch-mode
        --update-snapshots
        --no-transfer-progress &&
        cd ../
    - name: Prepare Vitruv DSLs submodule
      run: >
        cd Vitruv-DSLs &&
        ./mvnw clean install
        --fail-fast
        --batch-mode
        --update-snapshots
        --no-transfer-progress &&
        cd ../
    - name: Prepare Vitruv Main submodule
      run: >
        cd Vitruv &&
        ./mvnw clean install
        --fail-fast
        --batch-mode
        --update-snapshots
        --no-transfer-progress &&
        cd ../
    - name: Verify Transaction Manager
      run: >
        ./mvnw clean verify
        --batch-mode
        --update-snapshots
        --no-transfer-progress
